# Generated by Django 4.1 on 2022-08-14 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='status',
        ),
    ]
