# Generated by Django 4.1 on 2022-08-14 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_price',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
